README.md
test/capture_test.lua
test/capturing_test.lua
test/helpers_test.lua
test/hooks_test.lua
test/process_test.lua
test/server_test.lua

This rock should suggest the way of writing tests and follow them itself.

Rename local var for luatest from `lt` to `t`

---

.gitignore
CHANGELOG.md
bin/luatest
luatest/capture.lua
test/capture_test.lua
test/fixtures/error.lua
test/fixtures/fail.lua
test/fixtures/pass.lua
test/process_test.lua
test/runner_test.lua
test/server_test.lua

Fixes #13 
And some little fixes.

 Fix exit code when tests failed

---

CHANGELOG.md
bin/luatest
luatest/process.lua
test/process_test.lua

Kill GC'ed processes

---

CHANGELOG.md
luatest/capture.lua
test/capture_test.lua

Make capture work with large output

---

CHANGELOG.md
README.md
luatest/luaunit.lua
luatest/runner.lua
luatest/sandboxed_runner.lua
test/helper.lua
test/hooks_test.lua
test/runner_test.lua

 Make --shuffle option accept `group`, `all`, `none` values

---

luatest/luaunit.lua
luatest/reporting.lua
test/reporting_test.lua

Colorize report

---

.luacheckrc
Makefile
README.md
luatest/init.lua

Add 'Installation' section to readme

---

.luacheckrc
luatest/luaunit.lua

Fixes introducing global `clock`

Fix luacheck warnings in luaunit

---

CHANGELOG.md
luatest/luaunit.lua
test/luaunit_test.lua

Print tables in lua-compatible way in errors

---

CHANGELOG.md
README.md
luatest/capturing.lua
luatest/hooks.lua
luatest/luaunit.lua
test/capturing_test.lua
test/hooks_test.lua

Keep running other groups when group hook failed

---

luatest/luaunit.lua
test/luaunit/error_msg_test.lua
test/luaunit/utility_test.lua

Fix strings formatting in error messages

---

CHANGELOG.md
luatest/luaunit.lua
test/luaunit_test.lua

Assertions pretty-prints non-string extra messages

---

luatest/server.lua
test/server_test.lua

Add restart function for server
Also, add test for check restart was correct.

server: add restart function

---

CHANGELOG.md
README.rst
luatest/hooks.lua
test/hooks_test.lua

Add `before_test` and `after_test` hooks. They can be run for a specified test. `before_test` runs after `before_each` and `after_test` runs before `after_each`.
Close #141

Add `before_test` and `after_test` hooks.

---

README.rst
luatest/server.lua
test/server_test.lua

Syntactic sugar for using net_box eval

server: add convenient eval

---

luatest/server.lua

Add server alias in env space as 'TARANTOOL_ALIAS'

server: provide server alias in env vars

---

CHANGELOG.md
luatest/server.lua
test/server_test.lua

Server params will be reinitialized on start and restart
Close #149

Update server params on start

---

.github/workflows/push_rockspec.yaml

Fix all.rock push

---

CMakeLists.txt
cmake/FindTarantool.cmake

Closes #176
What has been done? Why? What problem is being solved?
Close #???

cmake: fix warning

---

luatest/runner.lua
test/runner_test.lua

Check test path exists before running tests

---

README.rst

- clarify how to run tests
- clarify how to run tests from a parameterized group
Closes #174
Closes #198

doc: update README file

---

README.rst

Fix typos in README that created warnings.

Fix documentation build warnings associated with luatest

---

CHANGELOG.md
README.rst
luatest/hooks.lua
luatest/runner.lua
test/fixtures/flaky_group.lua
test/luaunit/utility_test.lua
test/runner_test.lua

It is useful to have the option to repeat tests in the group in cycle.
There is only an option to run each test N times.
Closes #217

Add --repeat-group option

---

luatest/server_v2.lua

Slightly prettify docs in server_v2.lua for LDoc

---

luatest/server.lua
test/server_test.lua

When executing the following code on the remote server instance using `server:exec()`, we could get an unobvious error:
```lua
s = Server:new()
s:start()
-- we expected a custom error with the "My error" message, but
-- got "Transaction is active at return from function"
s:exec(function() box.begin() error("My error") end)
```
This is due to the specific evaluation and capture of the return values of `net_box:eval` (more detailed see here: https://github.com/tarantool/tarantool/issues/7288).
The error will be raised on the server instance side. In the process of development we found that our approach does not work in the specific case:
```lua
-- an error message has been expected but got an error table:
-- {
--	class = LuatestError,
--	status = fail,
--	message = "a value evaluating to …
```

Add error handling at the server instance level

---

CHANGELOG.md

- Remove entries that describe adding features related to not declared functionality.
- Remove entries that describe fixing functionality that was not released yet.
- Add missing entries that describe important bug fixes.
- Proofread some entries.

changelog: rm superfluous entries and add missing

---

luatest/output/tap.lua

Add missing tabulation to artifacts in tap output

---

luatest/server.lua
luatest/utils.lua
test/utils_test.lua

Simplify code from PR #351 based on @Totktonada advice.
Follows #350

server: refactor exec() sparse output support

---

CHANGELOG.md
luatest/assertions.lua
luatest/helpers.lua
luatest/hooks.lua
luatest/process.lua
luatest/replica_proxy.lua
luatest/replica_set.lua
luatest/runner.lua
luatest/server.lua

Everything is logged via new `luatest.log` module. Important and most popular modules improved by additional logs about internal states or logic. This should help in investigating problems.
Closes #325

Add more logs

---

luatest/assertions.lua
test/luaunit/assertions_error_test.lua

That is if there is `expected.prev` then it should cover `actual.prev` and so on recursively. Also make existing tests for `assert_error_covers` more precise.
Closes #372

Make assert_error_covers support stacked diagnostics
