tarantool/luatest

- CHANGELOG.md
- luatest/capture.lua
- test/capture_test.lua
`ffi.C.coio_wait` is replaced with `socket.iowait`
> Make capture work with large output v2

- README.md
> Remove links to LuaUnit docs from readme

- CHANGELOG.md
- luatest/init.lua
- luatest/luaunit.lua
- test/luatest_test.lua
Is it enough for #56 ? It does not print missing/different elements.
> Fix error messages for *_covers matchers

- CHANGELOG.md
- README.md
- luatest/init.lua
- luatest/luaunit.lua
- test/luatest_test.lua
- test/sub_dir/group_test.lua
- Raise error when `group()` is called with existing group name.
- Allow dot in group name.
- Prevent using `/` in group name.
- Decide group name from filename for `group()` call without args.
> Improvements for `group` method

- CHANGELOG.md
- luatest/luaunit.lua
- test/luatest_test.lua
- test/luaunit_test.lua
Luaunit added custom prefixes to error messages
to control flow (skip, success, failures in assertions).
It required to match this strings over all prefixes to find
out the valid status, which resulted in great performance
degradation when error message is quite large.
Now it throws tables with custom format, which has
desired node status in separate field.
> Fix performance issue with large errors messages

- luatest/helpers.lua
Fix typo in helpers.retrying from 'config.dalay' to 'config.delay'
> Fix typo in helpers.retrying

- luatest/luaunit.lua
- test/luaunit_test.lua
Before this patch raised non-string errors failed with:
- attempt to concatenate 'uint64_t' and 'string'
- attempt to concatenate 'struct error' and 'string'
- attempt to concatenate field 'msg' (a table value)
> Fix handling any non-string errors

- luatest/helpers.lua
- test/helpers_test.lua
Traceback provided by retrying error usually looks as follows:
```txt
363 =========================================================
364 Tests with errors:
365 ------------------
366 1) bootstrap.test_cookie_change
367 /.rocks/share/tarantool/luatest/helpers.lua:72: /.rocks/share/tarantool/luatest/server.lua:113: Network is unreachable
368 stack traceback:
369 	/.rocks/share/tarantool/luatest/helpers.lua:72: in function 'retrying'
370 	.../tarantool/cartridge/test/integration/bootstrap_test.lua:68: in function 'bootstrap.test_cookie_change'
```
Pointing on the helpers.lua is misleading, so this patch fixes it by eliminating unnecessary stack frames if the error occurs.
> Preserve stacktrace in helpers.retrying

- luatest/luaunit.lua
- test/luatest_test.lua
Make `assert_covers` matcher to fail with appropriate message
instead of:
```
bad argument #1 to 'pairs' (table expected, got nil)
```
> Fix type check in `assert_covers` matcher

- luatest/capture.lua
- luatest/ffi_io.lua
Start separate fibers for each pipe.
This allows to avoid unnecessary switches to the reader fiber
while pipe is empty and makes possible to capture stderr and stdout
independently without delay.
luatest's suit is faster by 20%.
Also extracted io-related functions to ffi_io module
for later reuse.
> Make Capture more responsive

- luatest/server.lua
Make log compatible with bash. Also command line arguments were missing.
Before the patch:
```bash
export TARANTOOL_FOO = foo export TARANTOOL_BAR = bar ./init.lua
```
After the patch:
```bash
TARANTOOL_FOO="foo" TARANTOOL_BAR="bar" ./init.lua "--alias" "dummy"
```
> Enhance server:start() logging

- luatest-scm-1.rockspec
When tarantool is installed outside /usr/local, cmake encounters
problems finding it. To determine the path it uses TARANTOOL_DIR hint,
which is passed from the rockspec external_dependencies.
See also: https://github.com/tarantool/modulekit/issues/2
> Fix tarantool headers lookup

- luatest/server.lua
- test/server_test.lua
Net.box connections shouldn't be cached if it's not active
> Fix server connect_net_box reconnecting

- CHANGELOG.md
- README.md
- luatest/init.lua
- luatest/luaunit.lua
- test/helper.lua
- test/luatest_test.lua
- test/luaunit/assertions_error_test.lua
- test/luaunit/assertions_test.lua
- test/luaunit/error_msg_test.lua
- test/luaunit/utility_test.lua
\+ Fix `assert_items_equals` for repeated values. Add support for `tuple` items.
Fixes #80
> Add assert_includes_items matcher

- CHANGELOG.md
- luatest/luaunit.lua
- test/luatest_test.lua
- test/luaunit/utility_test.lua
This makes it consistent for comparisons on any depth.
Before the patch these passed
t.assert_equals(tuple(1), tuple(1))
t.assert_equals(box.NULL, nil)
but these failed
t.assert_equals({tuple(1)}, {tuple(1)})
t.assert_equals({1, box.NULL, 2}, {1, nil, 2})
After the patch all assertions above pass.
Also fixed incorrect behaviour of `assert_not_equals`.
Fixes #90
> `assert_equals` uses same comparison rules for nested values

- .github/workflows/push_rockspec.yaml
- .github/workflows/test_on_push.yaml
- .gitignore
- test/capture_test.lua
This patch removes io_to_fio hack in favour a new one. Previous
version used fio metatable and it was broken after
tarantool/tarantool@3d5b4da. This patch just set file descriptor
numer to stdout (2) or stderr (3) when it required. So it seems
enough to solve this problem.
An alternative way is to use `struct fio_handle` directly. But it
seems more danger way than proposed.
Closes #112
> fix io to fio hack

- CHANGELOG.md
- luatest/output/text.lua
Now execution time is written for each test and verbose mode looks like this: 
```
assertions.test_assert_equals_for_cdata ... (0.010s) fail
/home/aleksandr/tarantool/luatest/test/assertions_test.lua:28: Received unexpected value: 1
server.test_http_request_post_json_with_custom_headers ... (0.012s) Ok
server.test_net_box ... (0.023s) Ok
server.test_inherit ... (0.005s) Ok
=========================================================
Ran 207 tests in 8.097 seconds, 207 successes, 0 failures
```
Close #128
> Write execution time for every test

- CHANGELOG.md
- luatest/output/generic.lua
- luatest/output/text.lua
- luatest/runner.lua
When capture is disabled test name is written twice: at the start and at the end with its result. 
```
output.test_tap_verbose_output ... 
1..8
...
output.test_tap_verbose_output ... (0.197s) Ok
```
Close #131
> Repeat tests' names

- CHANGELOG.md
- luatest/assertions.lua
- test/luaunit/error_msg_test.lua
If no error is generated during function call then `assert_error_msg_` assertions will print return value like this:
```
Function successfully returned: 4
Expected error: "bla bla bla"
``` 
Close #127
> Error assertions print return value

- luatest/runner.lua
- test/fixtures/flaky.lua
- test/runner_test.lua
"luatest -r 2" etc would terminate with
"attempt to concatenate field 'test_iteration' (a nil value)"
if some test would fail not on the first iteration.
Broken in 940b4c1
(Tue Dec 3 11:32:59 2019 +0300).
Reproducer (launch with "-r 2"):
```
g_flaky = t.group('flaky')
local counter = 1
g_flaky.test_flaky = function()
t.fail_if(counter > 1, 'Boo!')
counter = counter + 1
end
```
> Fix handling flaky tests

- luatest/output/tap.lua
Tap protocol is used to the first line as a line with the version.
> Add line with tap version to the tap output

- .github/workflows/destroy-deployment.yml
- .github/workflows/pull-translation.yml
- .github/workflows/push-translation.yml
- .github/workflows/upload-translations.yml
- .gitignore
- doc/README.md
- doc/cleanup.py
- doc/conf.py
- doc/crowdin.yaml
- doc/locale/ru/LC_MESSAGES/README.po
- doc/requirements.txt
Documentation sources are .rst files where a tech writer or a developer writes documentation. As soon as we have two languages supported on our website we need to maintain translated 100% of the documentation. For translation, we use Crowdin - saas solution for translating any texts.  
While a new PR with changes in .rst is opened, the translations for these changes are preparing by translators in Crowdin.  
When the translations are ready we can run __Pull translations__ job to download and commit translations into the PR branch.  
This diagram shows how the process works:
- add cleanup.py for re-arranging .po files and initial re-arranged .po files
- push-translation.yml push translation sources to Crowdin on pull request when .rst is changed, create a deployment with a link to Crowdin …
> Add pull/push workflow for translations

- .github/workflows/test_on_push.yaml
It's common nowadays to use `tarantool/setup-tarantool` Github Action. It makes CI faster by caching installed deb packages.
> Make use of setup-tarantool github action

- luatest/server.lua
- test/server_instance.lua
- test/server_test.lua
Previously, only localhost was supported for Servers as a listen port. This commit supports unix-socket way.
> server: make able to use sock as listen port

- CHANGELOG.md
- luatest/hooks.lua
- luatest/runner.lua
- test/hooks_test.lua
Repeat `_each` and `_test` hooks when `-r` option is specified.
Close #161
> Repeat _each / _test hooks

- CHANGELOG.md
- README.rst
- luatest/helpers.lua
- luatest/hooks.lua
- luatest/init.lua
- luatest/parametrizer.lua
- luatest/utils.lua
- test/fixtures/parametrized.lua
- test/helpers_test.lua
- test/parametrization_test.lua
Implement group parametrization
```lua
-- Define parametrized groups
local pg = t.group('pgroup', t.helpers.matrix({a = {1, 2}, b = {3, 4}}))
pg.test_example_1 = function(cg) ... end
-- type(cg.params.a) == 'number'
pg.test_example_n = function(cg) ... end
-- Hooks can be specified for one parameter
pg.before_all(function() ... end)
pg.before_each({a = 1}, function() ... end)
pg.after_each({b = 3}, function() ... end)
pg.after_test('test_example_1', {a = 2, b = 4}, function() ... end)
```
Test with specified params can be started from command line
```
luatest pgroup.a:2.b:3.test_example_1
```
Close #116
> Implement group parametrization

- test/server_instance.lua
Due to a race, sometimes it connects to the server before the proper permissions are granted. It results in the error: `Execute access to universe '' is denied for user 'guest'`
This patch fixes the race by granting permissions prior to listening
> Fix flaky server.test_unix_socket

- CHANGELOG.md
- README.rst
- luatest/server.lua
- luatest/utils.lua
- test/server_test.lua
Add new `Server:exec()` function which runs a Lua function remotely.
Usage:
```lua
local vclock = server:exec(function()
return box.info.vclock
end)
```
```lua
local sum = server:exec(function(a, b)
return a + b
end, {1, 2})
-- sum == 3
```
```lua
server:exec(function()
t.assert_equals(math.pi, 3)
end)
-- mytest.lua:12: expected: 3, actual: 3.1415926535898
```
Close #173
> Add server:exec method

- luatest-scm-1.rockspec
GitHub is going to disable unencrypted Git protocol, so `git://` URLs
will stop working soon (see [1]).
[1]: https://github.blog/2021-09-01-improving-git-protocol-security-github/
Part of https://github.com/tarantool/tarantool/issues/6587
> rockspec: use git+https:// for git repository URL

- CHANGELOG.md
- luatest/assertions.lua
- test/luatest_test.lua
- test/luaunit/error_msg_test.lua
The `assert_not_equals` function printed the following error message
when the values were equal:
Received unexpected value: <value>
This message sounds quite confusing because in this case the question
is raised: 'what is the expected value?'. But the expected value is any
value different from `<value>`. So the error message was changed to
Actual and expected values are equal: <value>
which is more comprehensible.
Closes #206
> Fix confusing err message from `assert_not_equals`

- luatest/hooks.lua
- test/hooks_test.lua
When a named test hook, that doesn't belong to any test (for example, if
someone makes a typo in test name), was being defined, it was impossible
to know about that. This might lead to unnecessary debugging actions
from the developer's side to understand what's going on and why the hook
is not running.
Now to catch such cases luatest checks that hooks are defined only for
existing tests and raises an error with a message like that:
There is no test with name '<test name>' but hook 'before_test' is 
defined for it
which should give glue to developers what is wrong.
Closes #205
> Check hooks are defined only for existing tests

- CHANGELOG.md
- README.rst
- luatest/assertions.lua
- test/luatest_test.lua
- test/luaunit/error_msg_test.lua
This patch fixes confusing docstrings for `assert_items_equals` and
`assert_items_include` functions and error messages that the functions
produce when asserting fails.
These functions do a comparison of actual and expected tables only by
field values (keys are not considered) but docstrings and error messages
made people think that field keys are considered as well which is wrong.
Closes #117
> Fix confusing doc strings and err messages

- CHANGELOG.md
- luatest/assertions.lua
- test/luatest_test.lua
When a test case contained the skip/skip_if/run_only_if function without
an optional message, luatest printed `nil` after the test status.
Now luatest prints the `(no reason specified)` message.
Closes #171
> Print message instead of `nil` value

- CHANGELOG.md
- luatest/server.lua
- test/server_test.lua
Since luatest supports in luatest/server.lua the socket connection to
tarantool instances via the net_box_uri param, we need to check that
the socket's path length is less than the max length of the Unix domain
socket path allowed by a system. 
Otherwise, we will get the `No buffer space available` error which is not 
clear for users and may take some time to understand what's wrong.
Closes #152
> Raise error if net_box_uri > max unix socket path

- CHANGELOG.md
- luatest/output/generic.lua
Until this moment luatest printed different test run summary reports
depending on how many tests succeeded, failed, xfailed, etc. It used
the plural form for test status nouns (success, fail, xfail, etc.)
if there were 0 or > 1 affected tests and the single form if it was 1
test.
It was decided to fix this inconsistency and use verbs in past simple
tense (succeeded, failed, xfailed, etc.) for all cases.
Closes #172
> Make test run summary report consistent

- luatest/runner.lua
According to the README, CLI arguments are treated as files or dir paths
when an argument contains '/' in it.
The help message confuses users who want to pass a test
filename to luatest:
Usage: luatest [options] [files or dirs ...] [testname1 ...]
To be consistent with the README, the `Usage` section is changed to:
Usage: luatest [options] [path ...] [group ...]
`testname1` changed with `group` to be consistent, as well as the
description which is moved from the `Options` section to the new
`Positional arguments` section.
Closes #155
> Describe positional arguments in the help message

- luatest/init.lua
- luatest/tarantool.lua
This patch adds a new module tarantool.lua to the repo that is a copy of
the test/luatest_helpers/misc.lua module [1] in the tarantool/tarantool
repo. The later should be deleted in the nearest future.
[1] https://github.com/tarantool/tarantool/blob/5c62f01bb6d7a88855108925b8ed0ba3ca344d2b/test/luatest_helpers/misc.lua
Part of #238
> Add new module tarantool.lua

- luatest/tarantool.lua
This patch adds a new function to the tarantool.lua module that is a
copy of the function in the test/luatest_helpers/fiber.lua module [1]
in the tarantool/tarantool repo. The fiber.lua should be deleted in
the nearest future.
[1] https://github.com/tarantool/tarantool/blob/256da01046da8f4fbe81d629cf54ae32dc04a1fb/test/luatest_helpers/fiber.lua
> Add new func `find_fiber_by_name` to tarantool.lua

- luatest/init.lua
- luatest/replica_conn.lua
- luatest/replica_proxy.lua
- luatest/tarantool.lua
This patch adds a new module replica_proxy.lua to the repo that is
a copy of the test/luatest_helpers/proxy/proxy.lua module [1] in the
tarantool/tarantool repo. The later should be deleted in the nearest
future.
The new module is intended to manage connection to Tarantool replication
instances via proxy.
Also, the replica_conn.lua module is added that is considered as an
internal one and not exposed to public API.
[1] https://github.com/tarantool/tarantool/blob/ad420846861a117b2b7e82b434acd1372c6abe08/test/luatest_helpers/proxy/proxy.lua
Part of https://github.com/tarantool/luatest/issues/251
> Add new module replica_proxy.lua

- README.rst
Removed a link to Travis CI which we don't use anymore.
> Remove link to travis-ci from the readme

- bin/luatest
Printing out tarantool version at bin/luatest.
Added method to printing out used tarantool version.
Resolves #240
> Print Tarantool version used by luatest 

- luatest/server.lua
It looks like the parameter was marked as a string one by a copy-paste mistake. Looking through the source code, it is clear that it should have the boolean type.
Fixes #119
> Change `coverage_report` parameter type to boolean

- luatest/init.lua
- luatest/server_v2.lua
- luatest/server_v2_instance.lua
This patch adds a new module server_v2.lua to the repo that is an
almost exact copy of the test/luatest_helpers/server.lua module [1]
in the tarantool/tarantool repo. The later should be deleted in the
nearest future.
The new module should be considered as an enhanced version of the old
one, where some significant features like waiting until the server is
up are available.
Also, the server_v2_instance.lua file is added that is considered as
an internal one and not exposed to public API.
[1] https://github.com/tarantool/tarantool/blob/bab289cd88a7f76bd1334853063066c43591fabe/test/luatest_helpers/server.lua
Part of #239
> Add new module server_v2.lua

- CHANGELOG.md
- luatest/server_instance.lua
The `box.ctl.set_on_shutdown_timeout()` function is available only since Tarantool 2.8.0-139-g357f15517. This patch makes the server_instance.lua script compatible with older Tarantool versions.
> Make server_instance.lua work for Tarantool < 2.8.1

- luatest/server.lua
- luatest/server_instance.lua
When luatest is installed as a rock, the internal server_instance.lua
script won't have execution permissions even though it has them in the
source tree, and won't be able to be run while a server start.
Let's start a server process as
/abs/path/to/tarantool /abs/path/to/luatest/server_instance.lua
instead of just
/abs/path/to/luatest/server_instance.lua
to bypass the problem.
Also, the shebang string and x-bit are removed from server_instance.lua.
Part of #269
> Fix instance file permissions when installing luatest as rock

- CHANGELOG.md
- config.ld
- luatest/init.lua
- luatest/replica_set.lua
- luatest/server.lua
This patch adds a new module replica_set.lua to the repo that is an
almost exact copy of the test/luatest_helpers/cluster.lua module [1]
in the tarantool/tarantool repo. The later should be deleted in the
nearest future.
[1] https://github.com/tarantool/tarantool/blob/943f7d1/test/luatest_helpers/cluster.lua
Part of #237
> Add new module replica_set.lua

- luatest/server.lua
- test/server_test.lua
Fix the following error:
LuajitError: /usr/bin/tarantool:1: unexpected symbol near 'char(127)'
fatal error, exiting the event loop
Fixes #274
> Fix server start issue when coverage is enabled

- .luacheckrc
- CHANGELOG.md
- luatest/init.lua
- luatest/server.lua
- test/autorequire_luatest_test.lua
- test/server_instance.lua
Luatest module available without explicit require:
```lua
g.server:exec(function()
t.assert(...)
end)
```
Resolves #233
> Autorequire luatest in server instances

- luatest/server.lua
`Server:grep_log` assumes that the Tarantool instance was restarted and resets search if it finds a string matching
`Tarantool %d+.%d+.%d+-.*%d+-g.*`
The problem is the warning message printed by `box.cfg()` if the instance needs a schema upgrade also matches this string:
```
W> Your schema version is 2.10.5 while Tarantool 2.11.0-entrypoint-945-gbd02451ff84d requires a more recent schema version. Please, consider using box.schema.upgrade().
```
[link to the code](https://github.com/tarantool/tarantool/blob/0479cfafc9615bc6eb69442f98735704c3bc5aa0/src/box/lua/load_cfg.lua#L1021-L1031)
Fix the search string to make sure this doesn't happen.
**NO CHANGELOG** because the luatest version where Server:grep_log was first introduced hasn't been released yet.
> Fix Tarantool restart detection in `Server:grep_log`

- .luacheckrc
- CHANGELOG.md
- luatest/init.lua
- luatest/server.lua
- test/autorequire_luatest_test.lua
- test/server_instance.lua
In the commit tarantool/luatest@58eae75 auto-requiring of the 'luatest'
lib was added to the `Server:eval()` function, so it was also available
in `Server:exec()`, and it was defined as `t` variable. In the process
of development we found that the following construction doesn't work due
to the upvalue error:
-- foo_bar_test.lua
...
g.test_foo_bar = function()
server:exec(function()
t.assert_equals(1, 1)  -- upvalues exception (!)
end)
end
To fix this error we decided to make the global variable `t` that had
the 'luatest' lib already loaded. So there was no need to import the
'luatest' lib in the test files and the following example worked:
-- foo_bar_test.lua
-- local t = require('luatest')  -- `t` is already defined
...
g.test_foo_bar = function() …
> Improve luatest auto-requiring in `Server:exec`

- CHANGELOG.md
- luatest/server.lua
- test/boxcfg_interaction_test.lua
- test/server_instance.lua
Server module(`server.lua`)  will contain two new wrappers for the interacting with the `box.cfg` variable on the remote server instance:
`server:update_box_cfg(cfg)`
`server:get_box_cfg()`
Performs a simple call to `box.cfg(cfg)` on server instance. `cfg` type must be table. if type is incorrect
will be write the follow error:
```
bad argument #2 to set_box_cfg (table expected, got <your_bad_type>)
```
Performs a simple call to `return box.cfg` on server instance. Method does not take parameters. It returns a table.
```lua
-- some_test.lua
server:update_box_cfg{read_only=true}
local cfg = server:get_box_cfg()
print(cfg.read_only) -- will printed `true`
```
Closes #232
> Add server wrappers for the `box.cfg` interaction

- CHANGELOG.md
- luatest/tarantool.lua
It helps to skip the test if package is not EE.
Part of https://github.com/tarantool/tarantool/issues/7718
> Add luatest.tarantool.skip_if_not_enterprise

- CHANGELOG.md
- luatest/server.lua
- luatest/utils.lua
- test/malformed_args_test.lua
Due to the specifics of the `unpack` function in the `server:exec()` method an array structure check has been added. An error will be raised if the arguments are not an array.
```lua
-- some_test.lua
server:exec(function(a, b)
-- `a` is 'a'
-- `b` is 'b'
end, {'a', 'b'})
server:exec(function()
-- nothing
end)
```
Due to the specific and non-deterministic `#` method, we cannot use this table attribute.
These cases will be skipped and will not be checked.
```lua
-- some_test.lua
server:exec(function(a)
-- nothing
end)
server:exec(function(a,b)
-- `a` is 'a'
-- `b` is nil
end, {'a'})
server:exec(function(a)
-- `a` is 'a'
--  the rest of the arguments are cut off
end, {'a', 'b'})
```
```lua
-- some_test.lua
server:exec(function(a,b,c)
-- `a` is 'a'
-- `b` is 'c' (!) shifted
-- `c` is nil
end, …
```
> Raise an error when non-array arguments passed to the `server:exec`

- CHANGELOG.md
- luatest/server.lua
- test/server_test.lua
There is a simple test via replica set:
```lua
-- some_test.lua
local cluster = require('luatest.replica_set')
cluster:new()
cluster:build_server(master, ...)
cluster:build_server(replica, ...)
cluster:add_server(master)
cluster:add_server(replica)
cluster:start()
```
This works fine if all servers are successfully started.
However, luatest will wait all the time (60s by default), even if something has happened to the process.
See the diagram for details:
Add process status check to waiting for condition:
```lua
-- server.lua
...
local function wait_for_condition(cond_desc, server, func, ...)
...
while true do
if not server.process:is_alive() then -- checks state of process
...
end
if fund(...) then
return
end
if clock.time() > deadline then -- checks time
...
end
fiber.sleep(WAIT_DELAY) …
```
> Raise an error in the `Server:wait_for_condition()` function when the server process is terminated

- CHANGELOG.md
- luatest/output/junit.lua
- luatest/output/tap.lua
- luatest/output/text.lua
- luatest/replica_set.lua
- luatest/runner.lua
- luatest/server.lua
- luatest/test_instance.lua
- luatest/utils.lua
- test/collect_rs_artifacts_test.lua
- test/collect_server_artifacts_test.lua
- test/replica_set_test.lua
- test/server_test.lua
Fixed the following error:
```lua
g.test_foo = function()
s = Server:new({box_cfg = {bad_option}}
s:start()  -- bad `box_cfg` value, the server process not started
s:drop()  -- kill failed: 256
end
```
The method was removed because there was an ambiguous understanding of the differences between the `stop()`, `drop()` and `clean()` methods.
Now, there are only two method:
- `drop()` - stops and perfoms a clean-up working directory of server object;
- `stop()` -  stops the server process and closes the connection.
If the test fails, all server artifacts (logs, xlogs, snapshots, etc.) will be saved to the `${VARDIR}/artifacts` directory for further analysis.
Default path for the test artifacts is `${VARDIR}/artifacts`.
How it will work:
- the test must contain any hook that calls the …
> Keep artifacts of server(logs, snap, etc) if test has been failed

- luatest/replica_conn.lua
- luatest/replica_proxy.lua
- luatest/utils.lua
- test/proxy_test.lua
When one end of the connection is closed for some reason, the proxy should close the other end as well. Otherwise random hangs are possible when a client doesn't notice that the server has closed the socket.
Previously clients never noticed leader disconnect (they only noticed that the heartbeats were missing), and some tests relied on that behaviour while proxy is paused. To preserve it, do not close the sockets while proxy is paused.
Resolves #298
> Fix random test hangs when using proxy module

- luatest/server.lua
Currently `wait_for_downstream` doesn't wait for replica to be up to date with master. It only checks, that downstream "knows" correct vclock of the replica by taking vclock of remote server and waiting for info.downstream.vclock to be the same. The function's comment says the opposite, so this is not expected behavior.
Let's take current vclock instead. This way the function will wait for remote server to apply all master's data and downstream to be up to date. Moreover, let's update function's comment to be less vague.
Closes tarantool/tarantool-qa#311
> Fix wait_for_downstream_to

- .github/workflows/test_on_push.yaml
- CMakeLists.txt
- test/assertions_test.lua
- test/autorequire_luatest_test.lua
- test/boxcfg_interaction_test.lua
- test/capturing_test.lua
- test/helpers/general.lua
- test/hooks_test.lua
- test/luatest_test.lua
- test/luaunit/assertions_error_test.lua
- test/luaunit/assertions_test.lua
- test/luaunit/error_msg_test.lua
- test/luaunit/utility_test.lua
- test/malformed_args_test.lua
- test/output_test.lua
- test/parametrization_test.lua
- test/pp_test.lua
- test/runner_test.lua
- test/server_test.lua
- test/xfail_test.lua
> Fow what test/helper.lua is needed?
Luatest automatically requires `test/helper.lua` file if it's present.
Usually, it is used to configure luatest or run any bootstrap code.
> What's the problem?
To run tarantool functional tests we use the test-run framework [1].
test-run has an integration with luatest (uses luatest as a submodule)
and allows us to run tarantool functional tests written in the luatest
approach. Most of the such tests can be run via luatest directly, but
test-run is used to run all types of tarantool tests at the same time
(diff, python, app, luatest).
When test-run works, it tunes some environment variables for own needs
and sets LUA_PATH to something like this:
LUA_PATH='<...>/tarantool/?/init.lua;<...>/tarantool/?.lua;\ …
> Not require own test helper when running tests

- luatest/server.lua
- test/server_test.lua
server.grep_log() has 'reset' option, which allows to reset the result, when instance restart is found. It doesn't work on Tarantool EE, as it tries to find "Tarantool %d+.%d+.%d+-.*%d+-g.*" pattern, but EE has "Tarantool Enterprise ...".
Let's use tarantool.package value instead of explicitly specifying, on which tarantool package restart is done.
Closes #319
> server: fix reset option in grep_log for Tarantool EE

- luatest/output/junit.lua
- luatest/output/tap.lua
- luatest/output/text.lua
- luatest/runner.lua
- luatest/server.lua
- luatest/test_instance.lua
- test/artifacts/common_test.lua
- test/artifacts/end_group_test.lua
- test/artifacts/hooks_test.lua
- test/artifacts/replica_set_test.lua
- test/artifacts/sequence_test.lua
- test/artifacts/start_group_test.lua
When creating the logic for saving artifacts [^1] a global variable has been created as `current_test` in the `runner.lua` module. Luatest has collected all the tests and  runs a simple loop. At the beginning of each iteration the current test is written to the `current_test`.
[^1]: tarantool/luatest#296
Server saved the value of the current test. However at some point the current test in the global variable and in the server object were different (the server stored information about the previous test). Also server does not store information about which test it was used in.
Redesign the logic of working with artifacts: now each test knows which server is linked to it, and each server knows about the test.
For example:
```lua
foo = Server:new()
bar = Server:new()
foo:start()
bar:start()
-- …
```
> Fix saving artifacts

- luatest/server.lua
The error has been replaced with a log entry (if the copying process failed, the current test will be marked as failed). Also, the PID of the server process was removed from the log string because the process may be missing.
Close #321
> Do not raise error in `save_artifacts` function

- CHANGELOG.md
- luatest/replica_set.lua
- luatest/runner.lua
- luatest/server.lua
- test/replica_set_test.lua
- test/server_test.lua
Now, luatest does not delete the server's working directory in the `Server:drop()` function. Instead of this, it deletes the whole var directory (default: `/tmp/t`) before running tests. So all server artifacts from all tests are saved after the run and can be analyzed.
However, you can disable this deletion by specifying the new `--no-clean` option.
- server artifacts are never deleted after the test run, so it takes some disk space;
- `--no-clean` - new option to disable deletion of the var directory before running tests.
```bash
$ ls /tmp/t
server-foo server-bar ...
$ ./bin/luatest -c -v ./test/new_test.lua
...
$ ls /tmp/t
server-new123
$ ./bin/luatest -c -v --no-clean ./test/new_test.lua
$ ls /tmp/t
server-new123 server-new456
```
Part of #308
> Not delete the server's working directory in `Server:drop()`

- luatest/runner.lua
- luatest/server.lua
Since commit [^1] the `Server:save_artifacts()` function was called more than once. Due to this fact we could overwrite already saved artifacts. Added a flag that will ensure that the saving will be executed only once.
There was also a problem when copying artifacts was not performed but the path to the artifacts was formed as a directory with artifacts:
```
artifacts:
server -> /tmp/t/artifacts/server-XXX
```
And if we tried to look at these artifacts, we could see this:
```
$ ls -la /tmp/t/artifacts/server-XXX
ls: cannot access '/tmp/t/artifacts/server-XXX': No such file or
directory
```
To show explicitly that the saving failed with an error, the following
string will now be written to the artifacts:
```
artifacts:
server -> Failed to copy artifacts for server (alias: server-XXX …
```
> Fix save artifacts

- luatest/assertions.lua
- test/assertions_test.lua
If the user makes a mistake in the `assert_error_msg_content_equals`:
t.assert_error_msg_content_equals("bad", error, "foo:1: bar")
where:
```
"bad" - excepted error message
error - built-in function (there may be another function here)
"foo:1: bar" - argument for the function
```
then the following error will be returned:
Error message expected: "bad"
Error message received: "foo:1: bar"
The user thinks that a comparison is being made between `foo:1: bar` and `bad`. He notices this error and at the same time can write the following:
t.assert_error_msg_content_equals("foo:1: bar", error, "foo:1: bar")
Now he will get the following error:
Error message expected: "foo:1: bar"
Error message received: "foo:1: bar"
It seems that the function doesn't work cause these strings are equal. In fact, …
> Improved error message for one assert function

- README.rst
As a part of https://github.com/tarantool/doc/issues/3730, we need to start recommending our users to utilize tt instead of the tarantoolctl utility.
> Replace tarantoolctl with tt

- .github/workflows/test_on_push.yaml
- CMakeLists.txt
- luatest/server.lua
Before this patch, it was impossible to run luatest unit tests with the coverage enabled because some tests failed with the following error:
luatest/test/server_test.lua:393: net_box is not connected
stack traceback:
...
[C]: in function 'xpcall'
artifacts:
server -> /tmp/t/artifacts/server-KLiHQDTbAJ4b
server -> /tmp/t/artifacts/server-QQQzEqDr4Hsy
This patch fixes the issue.
Also, it updates the name of the `make` target for running unit tests with coverage to `selftest-coverage` and enables coverage testing on CI.
> Fix running unit tests with coverage enabled

- CHANGELOG.md
- luatest/replica_proxy.lua
- luatest/server.lua
- luatest/utils.lua
- test/proxy_test.lua
- test/server_test.lua
Prior to this patch-set, box.cfg.listen was only set to string or number. Because of this, it was not possible to use the table as net_box_uri when creating the server. This patch-set allows the table to be used as net_box_uri. Also, now length of unix socket path is checked instead of length of whole URI. However, to support backward compatibility, the table representation of net_box_uri is converted to string.
Closes #341
Closes #342
> Accept table as net_box_uri

- CHANGELOG.md
- luatest/server.lua
- luatest/utils.lua
- test/autorequire_luatest_test.lua
- test/utils_test.lua
After [1], returning values after nil (for example, classic `return nil, err` scenario) is broken. This patch restores the behavior.  Since server doesn't always has access to `require('luatest.utils')`, utility is provided through its dump. Since `net.box` already handles `nil` args input with `box.NULL`, everything is fine for exec arguments.
1. https://github.com/tarantool/luatest/commit/e6a2093
- Documentation (bugfix)
Close #350
> server: restore exec() sparse output support

- CHANGELOG.md
- luatest/init.lua
- luatest/pp.lua
- luatest/utils.lua
You can use `luatest.log` for logging. This is convenient in case of debugging in several places at the same time:
```lua
local luatest = require('luatest')
luatest.log('outside')
g.test_foo = function()
luatest.log('inside')
g.server:exec(function() luatest.log('hi!') end)
end
I> outside
I> inside
I> hi!
```
The pretty conversion of arguments of any type will be performed automatically:
```lua
luatest.log('My structure is %s', {a = 1, b = 2, c = {cc = 1}})
I> My structure is {a = 1, b = 2, c = {cc = 1}}
```
Closes #326
> Add syntax sugar for more convenient logging

- CHANGELOG.md
- luatest/output_beautifier.lua
- luatest/runner.lua
- luatest/server.lua
- luatest/server_instance.lua
:heart: **We present a new functionality for logging** :heart:
Having written a simple test with two servers (bob and frank) we would like to see the output of each of them and also what is going on in the test itself. For example:
g.test_with_bob_and_frank = function()
g.bob:exec(function()
require('log').info('Hi, Frank!')
end)
g.frank:exec(function()
require('log').info('Hi, Bob!')
end)
require('log').info('Hi, Bob and Frank!')
end
In order to see their greetings, we had to look over each server log file:
$ cat /tmp/t/${BOB_VARDIR}/bob.log
...
2023-12-19 18:34:26.305 [84739] main/109/main I> Hi, Frank!
$ cat /tmp/t/${FRANK_VARDIR}/frank.log
...
2023-12-19 18:34:26.306 [84752] main/109/main I> Hi, Bob!
And there was no way to see the "Hi, Bob and Frank!" log message.
Now, if we provide …
> Add logging to unified file

- luatest/init.lua
- luatest/log.lua
- luatest/utils.lua
We improved `luatest.log` module for convenient logging and refactored it:
t.log('Info log: %s', 'foo')
t.log.warn('Warn log from %s', 'foo')
The following functions of the `luatest.log` module are presented:
t.log.error(msg[, args])
t.log.warn(msg[, args])
t.log.info(msg[, args])
t.log.verbose(msg[, args])
t.log.debug(msg[, args])
t.log() - syntax sugar for t.log.info(...)
Follows #326
> Improve log submodule of luatest

- CHANGELOG.md
- luatest/server.lua
Memory leak detection may occur when working with the server:
```lua 
g.test_foo = function()
...
g.server:exec(function()
-- there is an error from LeakSanitizer in `stderr` here
end)
g.server:exec(function()
-- server is alive
end)
t.assert(true)
end)
g.after_all(function()
g.server:drop() -- `test_foo` has passed
end)
```
We have added a check for the `LeakSanitizer` substring in `stderr` of the server process. If it's found, an error will be thrown and test will fail.
Closes https://github.com/tarantool/luatest/issues/349
ℹ️ P.S. Although this PR solves the problem described in #349, there may be a more elegant solution to such detections. It is described in more detail in #358
> Add memory leak detection during server process execution 

- CHANGELOG.md
- luatest/log.lua
Use `select()` to avoid `bad argument #3 to '?' (no value)` error in following example:
```lua
luatest.log('%s and %s', cdata<void *>: NULL, nil)
```
Closes #360
> Improve `luatest.log` function if a `nil` value is passed

- CHANGELOG.md
- config.ld
- luatest/init.lua
- luatest/justrun.lua
- test/justrun_test.lua
The original `justrun` module (path: tarantool/test/justrun.lua) has been moved to the current project with minor changes and will be available as follows:
```lua
t.justrun.tarantool(...)
```
This module works with the `popen` module which requires Tarantool 2.4.1 and newer. Otherwise `justrun.tarantool(dir, env, args[, opts])` will cause an error.
Closes #365
> Migrate `justrun` module and adapt it

- CHANGELOG.md
- luatest/server.lua
- test/server_test.lua
This patch changes the error message when the Unix socket path length exceeds a certain limit.
Follow-up #341
> server: change error message for unix socket path

- .github/workflows/test_on_push.yaml
- CHANGELOG.md
- CMakeLists.txt
- config.ld
- luatest/cbuilder.lua
- luatest/init.lua
- test/cbuilder_test.lua
- test/luatest_test.lua
The original `cbuilder` module (tarantool/test/config-luatest/cbuilder.lua) has been moved to the current project with minor changes and will be available as follows:
```lua
t.cbuilder:new(...)
```
The helper requires Tarantool 3.0.0 and newer. Otherwise `Builder:new()` will cause an error.
We've switched to using the `tt` utility instead of `tarantoolctl` when testing on versions 3.0 ([link](https://github.com/tarantool/tarantool/issues/9443)).
We've also fixed the tests for `box.tuple`, so the interface of `new()` function has changed ([link](https://github.com/tarantool/tarantool/releases/tag/3.0.0)).
> Migrate `cbuilder` module and adapt it

- CHANGELOG.md
- luatest/runner.lua
- test/luaunit/utility_test.lua
These options allow an external runner (such as [test-run][test-run]) to run the test cases separately: isolated and/or parallel.
The idea is the following.
* test-run has some criteria, whether to parallelize the given test.
* If it needs to be parallelized, test-run invokes `luatest --list-test-cases <..path to test..>`.
* Then each test case is run in its own process using `luatest --run-test-case <..test case..> <..path to test..>`.
The `--run-test-case` option may be simulated using `--pattern`, but it requires regexp escaping. It is more convenient to have a separate option to pass a verbatim test case name.
The new CLI options are mostly for scripting and not for interactive use. So, no short option are added for them.
[test-run]: https://github.com/tarantool/test-run
> Add --list-test-cases and --run-test-case

- test/autorequire_luatest_test.lua
`test_exec_when_luatest_not_found` fails if `luatest` is installed into `/usr/share/tarantool`.
Zap `LUA_PATH` to ensure that `require('luatest')` reports the 'module not found' error.
> test: don't fail if luatest is in system paths

- CHANGELOG.md
- README.rst
- config.ld
- luatest/group.lua
- luatest/hooks.lua
- luatest/init.lua
- luatest/runner.lua
- luatest/treegen.lua
- test/hooks_test.lua
- test/treegen_test.lua
Preloaded hooks extend base hooks. They behave like the pytest fixture with the `autouse` parameter. This is useful when writing a module and using it with "auto" before/after hooks.
The following functions have been "preloaded" into `hooks.lua` module:
- before_suite_preloaded(func)
- after_suite_preloaded(func)
- before_all_preloaded(func)
- after_all_preloaded(func)
- before_each_preloaded(func)
- after_each_preloaded(func)
Closes #380
The original `treegen` module (path: tarantool/test/treegen.lua) has been moved to the current project with the following changes:
- refactoring;
- updated documentation.
Closes #364
> Migrate `treegen` module and adapt it

- CHANGELOG.md
- luatest/server.lua
- luatest/utils.lua
You can use a declarative config file to configure a server instance via the following options:
- config_file (optional) Declarative YAML configuration for a server
instance. Used to deduce advertise URI to connect `net.box` to the
instance. The special value '' means running without `--config ...`
CLI option (but still passes `--name <alias>`).
- remote_config (optional) If `config_file` is not passed, this config
value is used to deduce the advertise URI to connect `net.box` to
the instance.
Close #367
> Adapt the server to use the declarative config

- luatest/runner.lua
Currently, it's created in the current directory, which is annoying.
Not adding a change log because this issues fixes commit f8a1c10baa482, which hasn't been released yet.
Closes #373
> Create luatest.log file in VARDIR

- CHANGELOG.md
- luatest/runner.lua
The option `-c` allows to disable capture and this option has no long variant with self-explained name.
The patch fixes that.
Closes #391
> Add a long option --no-capture

- CHANGELOG.md
- luatest/server.lua
- test/server_test.lua
Commit e6a209378038 ("Add error handling at the server instance") broke assertion failure reporting in `server:exec()` in case verbose error serialization is enabled in Tarantool (`box_error_serialize_verbose` compatibility option is set to `new`).
The problem is with the verbose error serialization, a raw string raised with `error()` is converted to an error object when marshalled through IPROTO while the `server:exec()` code expects it to remain a string because it encodes the original error in JSON. As a result, we get a mangled error like
```
{"status":"fail","class":"LuatestError","message":"...some_test.lua:42: expected: a value evaluating to true, actual: false"} {"code":32,"type":"LuajitError","trace":[{"file":"./src/lua/utils.c","line":687}]}
```
instead of
``` …
```
> server: fix assertion error serialization in exec()

- CHANGELOG.md
- README.rst
- luatest/assertions.lua
- luatest/comparator.lua
- test/luaunit/assertions_test.lua
This patch adds the `assert_items_exclude(actual, expected, message)` matcher. This matcher can be useful, for example, to verify that gc is working correctly.
> Add `assert_items_exclude` matcher

- CHANGELOG.md
- luatest/assertions.lua
- luatest/runner.lua
- luatest/server.lua
- luatest/utils.lua
- test/fixtures/trace.lua
- test/luaunit/utility_test.lua
- test/runner_test.lua
If a function executed with `Server:exec()` fails, luatest prints the stack trace only up to the `Server:exec()` call. If the failure happens to be in a nested function, this makes it impossible to figure out what happened.
Let's propagate the error stack trace from the server to the runner and make the runner concatenate it with its own stack trace. To achieve that, we wrap errors raised by the function executed by `Serer:exec()` to save the trace.
Closes #396
> Propagate stack trace from Server:exec()

- CHANGELOG.md
- luatest/assertions.lua
- luatest/helpers.lua
- luatest/hooks.lua
- luatest/log.lua
- luatest/output_beautifier.lua
- luatest/pp.lua
- luatest/process.lua
- luatest/replica_set.lua
- luatest/runner.lua
- luatest/server.lua
- test/luatest_test.lua
The goal of this PR is to fix spamming stdout on test failure with unified logging is enabled. Apart from that, it also brings a few improvements to unified logging.
Close #382
> Logging improvements

- CHANGELOG.md
- config.ld
- luatest/cluster.lua
- luatest/init.lua
- test/cluster_test.lua
The original `cluster` module (tarantool/test/config-luatest/cluster.lua) has been moved to the current project and will be available as follows:
```lua
local cluster = t.cluster:new(...)
cluster:start()
```
It is used to simplify managing Tarantool clusters based on the provided configuration. The helper requires Tarantool 3.0.0 or newer. Otherwise cluster methods cause an error.
Original helper created by: alexander.turenko@tarantool.org
Test author: vdavydov@tarantool.org
Closes #368
> Migrate cluster module and adapt it

- luatest/log.lua
Before commit 6c5c8b738525 ("Print luatest logs to stdout when unified log is disabled"), luatest implicitly configured the logger to operate in the non-blocking mode by using a pipe for the logs destination. Now, it uses a file albeit the file actually points to a pipe file descriptor. Tarantool thinks it's a regular file and writes all logs in the blocking mode. This leads to a deadlock if a test performs a lot of checks (which are logged) without yielding execution to the fiber processing logs because the size of a pipe is quite limited. Let's fix this issue by writing all logs through a pipe, as we did before. Let's also explicitly enable non-blocking logging to avoid breakages like this in future.
The fix isn't ideal because it may lead to dropping logs. We should probably handle …
> Fix deadlock in case test performs lots of checks without yielding

- CHANGELOG.md
- luatest/cluster.lua
- test/cluster_test.lua
Currently, `cluster:sync()` leaves instances removed from the config in the instance list. This makes `cluster:reload()` fail because it tries to reload the config for all instances including those that are not in the config anymore. To fix that, let's make `cluster:sync()` move instances that were removed from the config to the special expelled instance list so that they become inaccessible via cluster but are still dropped by `cluster:drop()`.
Also, let's add the new boolean option `start_stop` for `cluster:sync()`. If set, `cluster:sync()` will stop old servers and start new ones.
Closes #423
> cluster: expel instances removed from config in cluster.sync
